### ISSUE TITLE
Lag

### ISSUE THREAD

**Issue by lefevrG** [gsotti/EqualizerView#1]
Hey !

First, great lib :)

I got lag whatever number of bar i set, any tips ?

**Comment by gsotti** [comment]
Hey lefevrG,

First of all Thanks :)

I just updated the library, please check the sample app, and change the values for animation duration and animation values. Smaller animation-count and smaller duration should prevent the view from lagging.

If not please give me some more information about your device and Android version.

greeting from austria

**Comment by gsotti** [comment]
Hey,

just updated the lib again, and removed the animation count and set the repeat type to reverse, this should create smoother animation.
