### ISSUE TITLE
Library doesn't work in battery save mode

### ISSUE THREAD

**Issue by ViktorSkabiak** [gsotti/EqualizerView#2]
On Nexus devices  ( I've tested on nexus 5 with api 23) in battery save mode -  this library doesn't work at all. And it will not work,  becasue Object Animator not works in batery save mode. Try it. Enjoy. Have a nice day.

**Comment by gsotti** [comment]
Hey Viktor

thanks for your hint! Seems like not only object animator is not working, but all built-in animations stop working if battery save mode is on. 

In this case i just updated the lib, to play a "animation" as well, not as smooth as with the animator but acceptable.

But you have to enable it by setting "mRunInBatterySafeMode" to true.

thanks, you too.
